/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        System.out.println("Converter para Fahrenheit(F) ou Celsius(C)?");
        String tipo = sc.next().trim().toUpperCase();

        if (!tipo.equals("F") && !tipo.equals("C")) {
            tipo = "Opção inválida";
        }

        System.out.println("Digite a temperatura a ser convertida: ");
        double temperatura = sc.nextDouble();

        TempConverter tempConverter = new TempConverter();
        tempConverter.setTipo(tipo);
        tempConverter.setTemperatura(temperatura);

        System.out.println(tempConverter.calcular());

        sc.close();
    }
}
